#!/bin/bash

set -e

patch_prefix=$patch_dir/$patch_filename_prefix
command=$1

$command    ${patch_prefix}device_samsung_galaxys2-common.patch     $android_dir/device/samsung/galaxys2-common
$command    ${patch_prefix}kernel_samsung_smdk4412.patch            $android_dir/kernel/samsung/smdk4412

